---
title: "NO2 tables"
author: "Carles Milà"
date: "2/8/2020"
output: word_document
---

```{r libraries}
library("lubridate")
library("tidyverse")
library("readxl")
```

```{r read data}
# Read data
station_data <- read_csv("data/stations/clean_stationdata.csv")
calendar <- read_excel("data/other/calendar.xlsx") %>%
  mutate(start = as.Date(start),
         end = lead(start, 1),
         name = fct_inorder(name)) %>%
  filter(name != "End restrictions")
calendar$end[nrow(calendar)] <- as.Date("2020-07-26")  
calendar_grid <- tibble(date = seq(as.Date('2020-01-01'), as.Date('2020-07-26'), by = 'day')) 
calendar_grid$phase <- calendar_grid$date %>% 
  map_chr(~as.character(filter(calendar, start <= . & end >= .)$name[1]))
```

```{r prepare data}
# Time series change 
station_data <- station_data %>%
  mutate(Station = ifelse(type %in% c("industrial", "traffic"), "industrial and traffic", type)) %>%
  filter(date <= as.Date("2020-07-26"))
st2019 <- filter(station_data, year(date)==2019) %>%
  group_by(AirQualityStation) %>%
  summarise(no2_2019 = mean(no2)) %>%
  ungroup()
st2020 <- filter(station_data, year(date)==2020) %>%
  left_join(st2019, by = "AirQualityStation") %>%
  mutate(no2_change = no2/no2_2019 * 100) %>%
  left_join(calendar_grid, by = "date") %>%
  mutate(phase = fct_inorder(phase))
```

```{r calculate table}
res_change <- st2020 %>%
  group_by(phase, Station) %>%
  summarise(mean_change = mean(no2_change)) %>%
  pivot_wider(names_from = Station, values_from = mean_change)
res_change_all <-  st2020 %>%
  group_by(phase) %>%
  summarise(all = mean(no2_change))
res_all <- left_join(res_change, res_change_all, by = 'phase')
res_all <- mutate_if(res_all, is.numeric, function(x) paste0(round(x, 1), "%"))
knitr::kable(res_all)
```

